- hosts: namenode
  tasks:
  - name: "Creating a directory for hadoop softwares"
    file:
            state: directory
            path: "/root/hadoop"
  - name: "Copying the jdk file"
    copy:
            src: "/root/jdk-8u171-linux-x64.rpm"
            dest: "/root/hadoop/"
  - name: "Copying the hadoop file"
    copy:
            src: "/root/hadoop-1.2.1-1.x86_64.rpm"
            dest: "/root/hadoop/"
  
  - name: "Installing JDK"
    shell: "rpm -i /root/hadoop/jdk-8u171-linux-x64.rpm  --force"
  
  - name: "Installing Hadoop"
    shell: "rpm -i /root/hadoop/hadoop-1.2.1-1.x86_64.rpm  --force "

  - name: "Creating the directory for Hadoop Namenode"
    file:
            state: directory
            path: "/nn"

  - name: "Copying the hdfs file"
    copy:
            src: "/root/ansible_tasks/hadoop_config/master_files/hdfs-site.xml"
            dest: "/etc/hadoop/"

  - name: "Copying the core file"
    copy:
            src: "/root/ansible_tasks/hadoop_config/master_files/core-site.xml"
            dest: "/etc/hadoop/"

  - name: "Formatting the namenode"
    shell: "echo Y | hadoop namenode -format"

  - name: "Starting the hadoop namenode services"
    shell: "hadoop-daemon.sh start namenode"

  - debug:
          msg: "Hadoop Namenode started"
  


  
- hosts: datanode
  tasks:
  - name: "Creating a directory for hadoop softwares"
    file:
            state: directory
            path: "/root/hadoop"
  - name: "Copying the jdk file"
    copy:
            src: "/root/jdk-8u171-linux-x64.rpm"
            dest: "/root/hadoop/"
  - name: "Copying the hadoop file"
    copy:
            src: "/root/hadoop-1.2.1-1.x86_64.rpm"
            dest: "/root/hadoop/"

  - name: "Installing JDK"
    shell: "rpm -i /root/hadoop/jdk-8u171-linux-x64.rpm  --force"

  - name: "Installing Hadoop"
    shell: "rpm -i /root/hadoop/hadoop-1.2.1-1.x86_64.rpm  --force "

  - name: "Creating the directory for Hadoop Datanode"
    file:
            state: directory
            path: "/dn1"

  - name: "Copying the hdfs file"
    copy:
            src: "/root/ansible_tasks/hadoop_config/slave_files/hdfs-site.xml"
            dest: "/etc/hadoop/"

  - name: "Copying the core file"
    copy:
            src: "/root/ansible_tasks/hadoop_config/slave_files/core-site.xml"
            dest: "/etc/hadoop/"

  - name: "Starting the hadoop datanode services"
    shell: "hadoop-daemon.sh start datanode"

  - debug:
          msg: "Hadoop datanode 1 started"

