- hosts: all
  vars:
          - docker_image_pull: "httpd"
          - docker_image_launch: "httpd"
          - dir_name: "/task"
  tasks:

  - name: "Yum configuration of the docker"
    yum_repository:
          name: "Docker-ce"
          description: "Yum repo from Docker-ce"
          baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
          gpgcheck: "no"

  - name: "Installation of the docker package"
    package:
          name: "docker-ce-18.09.1-3.el7.x86_64"
          state: present

  - name: "Starting of the docker services"
    service:
          name: "docker"
          state: started
          enabled: yes

  - name: "Installation of the docker sdk for python library" 
    pip:
          name: "docker-py"

  - name: "Pulling the docker image from the docker hub"
    docker_image:
          name: "{{ docker_image_pull }}"
          source: pull
  
  - name: "Creating the directory to create html file"
    file: 
          path: "{{ dir_name }}"
          state: directory

  - name: "Copy the html code to the created directory"
    copy: 
          dest: "{{ dir_name }}/index.html"
          content: "Hey, this is the task_10 of the arth"

  - name: "Creating the docker container"
    docker_container:
          name: "httpd_task6"
          image: "{{ docker_image_launch }}"
          state: started
          ports:
          - "9999:80"
          volumes: "{{ dir_name }}:/usr/local/apache2/htdocs"

